import type { TechniqueText } from "./techniques";

// English text for each technique. Structure (level, difficulty, related) lives in techniques.ts.
export const TECH_EN: Record<string, TechniqueText> = {
  "full-house": {
    name: "Full House",
    alias: "Last Digit",
    summary: "A row, column or box has only one empty cell left: fill in the missing digit.",
    rule: "A unit already holds 8 digits → its last empty cell takes the 9th.",
    idea: [
      "Every row, column and box must contain each digit from 1 to 9 exactly once. When a unit already holds eight digits, the missing one has only one place to go: the single empty cell.",
      "It is the simplest technique of all, yet easy to miss while you are looking elsewhere. Each time you place a digit, glance at its row, column and box to see whether one of them has just reached 8 of 9.",
    ],
    spot: [
      "Count the empty cells in each row, column and box — any unit with exactly one is a target.",
      "Watch the units you have just added a digit to: they are the most likely to hit 8 of 9.",
      "Find the missing digit by counting 1 to 9, or by subtracting the sum of the present digits from 45.",
    ],
    pitfalls: ["Counting in a hurry gives the wrong missing digit — double-check with the sum of 45 if in doubt."],
  },
  "hidden-single-box": {
    name: "Hidden Single in a Box",
    alias: "Cross-hatching",
    summary: "Pick a digit and a box, cast rays from the copies of that digit, and find the only cell still able to take it.",
    rule: "In a box, digit d has only one cell no ray reaches → that cell is d.",
    idea: [
      "Switch the question from \"which digit goes in this cell?\" to \"where does the 5 of this box go?\". Every box must contain a 5, and every 5 already on the board blocks its whole row and column. We call that a ray.",
      "Cast rays from every 5 onto the box you are studying. Empty cells on a ray are out, and so are cells that already hold a digit. If only one cell is left, the box's 5 must be there — even if, viewed on its own, that cell still has several options.",
      "This is the technique players use most, and usually the fastest way to find digits early in a puzzle.",
    ],
    spot: [
      "Start with the digit that appears most often on the board: it casts the most rays.",
      "Scan by band: three boxes side by side share three rows. If two of them already have digit d, the third has only one row left for d.",
      "Boxes with few empty cells tend to give quick results.",
    ],
    pitfalls: ["Forgetting that cells which already hold a digit cannot take d either.", "Scanning only rows and forgetting columns, or the other way round."],
  },
  "hidden-single-line": {
    name: "Hidden Single in a Row or Column",
    alias: "Hidden Single (line)",
    summary: "In a row or column, a digit has exactly one cell left where it can go.",
    rule: "In a row (column), digit d has only one valid cell → that cell is d.",
    idea: [
      "The same idea as the hidden single in a box, but the unit is a row or a column. For each empty cell in the row, ask two questions: does this cell's column already have d? Does its box already have d? If so, the cell is blocked.",
      "It is a little harder to see because the blocking rays come from two directions: along columns (across the row) and from boxes. It is especially useful when a row or column has only 3–4 empty cells left.",
    ],
    spot: ["Pick a row or column with few empty cells, list the missing digits, and try each one.", "For each missing digit, mark which cells are blocked by their column or their box."],
    pitfalls: ["Checking only the column and forgetting the box: a d in the same box blocks the cell too."],
  },
  "naked-single": {
    name: "Naked Single",
    alias: "Sole Candidate",
    summary: "A cell sees 8 different digits in its row, column and box, so only one possibility is left.",
    rule: "A cell's row + column + box contain 8 different digits → the cell is the 9th.",
    idea: [
      "This technique looks from the cell's side. Each cell \"sees\" 20 others: 8 in its row, 8 in its column and 4 more in its box. Collect the digits in those cells; if there are 8 different ones, the missing digit is the answer.",
      "Once every cell has its candidates written in, naked singles stand out: they are cells with a single candidate. Without pencil marks you have to count, which is why this technique usually comes after the hidden singles run out.",
    ],
    spot: ["Favour cells where a busy row crosses a busy column.", "With pencil marks: look for a cell with just one small digit."],
    pitfalls: ["Counting the same digit twice (say a 4 in both the row and the box) and thinking you already have 8."],
  },
  pointing: {
    name: "Locked Candidates: Pointing",
    alias: "Pointing Pair/Triple · Locked Candidates Type 1",
    summary: "In a box, digit d lies on a single row (or column), so d is removed from the rest of that row (column).",
    rule: "Box B has d only on row R → remove d from row R outside box B.",
    idea: [
      "Every box must contain one d. If all the possible places for d inside the box lie on the same row, we don't yet know which cell it is, but we do know it is on that row, inside the box.",
      "That row can hold only one d — and it has already been reserved inside the box. So no other cell of the row, outside the box, can be d. The candidates in the box \"point\" along the row and clear d on the way.",
    ],
    spot: [
      "When scanning for hidden singles in a box leaves 2–3 cells, check whether they line up.",
      "It often appears when a box has empty cells on only one row or one column.",
    ],
    pitfalls: [
      "Getting the direction wrong: pointing removes d along the row outside the box, and nothing inside the box.",
      "The candidate cells must all be on one row; two cells on two different rows do not count.",
    ],
  },
  claiming: {
    name: "Locked Candidates: Claiming",
    alias: "Box/Line Reduction · Locked Candidates Type 2",
    summary: "In a row (column), digit d lies inside a single box, so d is removed from the other cells of that box.",
    rule: "Row R has d only inside box B → remove d from box B outside row R.",
    idea: [
      "This is pointing in reverse. The row must contain one d; if every possible place for d in the row falls inside the same box, the row's d is in that box.",
      "The box can hold only one d too, and the row has \"claimed\" it. So no other cell of the box, off that row, can be d.",
    ],
    spot: [
      "Look at rows and columns with few empty cells: if the cells that can still take d all sit in one three-cell segment, try claiming.",
      "Every box/line intersection can be used in one of two directions: pointing or claiming.",
    ],
    pitfalls: ["Mixing it up with pointing: pointing starts from the box, claiming starts from the row or column."],
  },
  "naked-pair": {
    name: "Naked Pair",
    alias: "Naked Pair · Locked Pair",
    summary: "Two cells in a unit have the same two candidates only, so those digits are removed from the rest of the unit.",
    rule: "Two cells in a unit hold only {x, y} → remove x and y from the other cells of the unit.",
    idea: [
      "If two cells in a row can only be 3 or 7, one of them is 3 and the other is 7. We don't know which is which, but the row's 3 and 7 are certainly reserved for those two cells.",
      "So no other cell in the row can be 3 or 7. If the two cells also share a box, you can eliminate in the whole box as well.",
    ],
    spot: ["Find cells with exactly two candidates, then compare them with cells in the same row, column and box.", "The two cells must have exactly the same two candidates: {3, 7} and {3, 7}, not {3, 7} and {3, 8}."],
    pitfalls: [
      "Two cells that are merely close but not in the same unit are not a naked pair.",
      "Missing candidates create fake pairs. Write in all candidates before looking for pairs.",
    ],
  },
  "hidden-pair": {
    name: "Hidden Pair",
    alias: "Hidden Pair",
    summary: "Two digits can only go in the same two cells of a unit, so every other candidate is cleared from those cells.",
    rule: "In a unit, x and y appear only in cells A and B → A and B keep only {x, y}.",
    idea: [
      "A hidden pair is seen from the digits' side rather than the cells'. If in a column the 2 can only go in cells A and B, and the 6 can only go in those same two cells, then A and B must be 2 and 6 in some order.",
      "Both cells are taken by 2 and 6, so every other candidate in A and B goes. It is called hidden because the extra candidates hide it; once they are cleared, the hidden pair becomes a naked pair.",
    ],
    spot: [
      "For each unit, count how many places each digit has left. Two digits that each have exactly two places, and the same two, form a hidden pair.",
      "They show up in units with many empty cells, where naked pairs are rare.",
    ],
    pitfalls: ["Both digits must have exactly two places, and the same ones; a digit with three places does not qualify."],
  },
  "naked-triple": {
    name: "Naked Triple",
    alias: "Naked Triple",
    summary: "Three cells in a unit share just three candidates between them, so those digits are removed from the rest of the unit.",
    rule: "Three cells in a unit whose candidates together are {x, y, z} → remove x, y, z from the rest of the unit.",
    idea: [
      "The naked pair extended: three cells, three digits. The digits x, y, z must fill these three cells, so there is no room for them elsewhere in the unit.",
      "The common trap: no cell needs to have all three candidates. {1, 4}, {4, 8}, {1, 8} is a valid naked triple, because together they hold only 1, 4 and 8.",
      "The general rule: N cells in a unit whose candidates together are exactly N digits lock those digits into those cells. With N = 4 you get a naked quad, which is rare.",
    ],
    spot: ["Find cells with 2–3 candidates in the same unit and try grouping them in threes.", "Units with many empty cells but a few \"poor\" cells are worth a look."],
    pitfalls: ["If the three cells together hold four digits, it is not a naked triple.", "All three cells must be in the same unit."],
  },
  "hidden-triple": {
    name: "Hidden Triple",
    alias: "Hidden Triple",
    summary: "Three digits appear in only the same three cells of a unit, so every other candidate is cleared from those cells.",
    rule: "In a unit, x, y, z lie only in 3 cells → those 3 cells keep only {x, y, z}.",
    idea: [
      "The hidden pair extended: three digits need three places, and only three cells contain them. Those cells belong to these three digits; every other candidate in them goes.",
      "Each digit does not have to appear in all three cells — it is enough that all their positions fit inside the three cells.",
      "Hidden and naked sets always come together: in a unit with k empty cells, a hidden set of n cells matches a naked set of k − n cells in the rest. Look for whichever is smaller.",
    ],
    spot: ["Count the places of each digit in the unit; take the digits with 2–3 places and try grouping them in threes.", "This is the hardest technique at this level to spot by eye — use it when the others have run out."],
    pitfalls: ["Including a digit that has four places in the triple."],
  },
  "x-wing": {
    name: "X-Wing",
    alias: "X-Wing · 2×2 fish",
    summary: "Digit d in two rows lies only in the same two columns, so d is removed from the other cells of those columns.",
    rule: "Two rows have d only in the same two columns → remove d from those columns in every other row (rows ↔ columns also works).",
    idea: [
      "Pick a digit d. If in row A d has only two places, and in row B d also has only two places in exactly the same two columns, the four cells form the corners of a rectangle.",
      "Each row needs one d, and the two must be in different columns. There are only two ways: along one diagonal or the other — an X. Either way each column already gets its d from row A or row B, so the other cells in those two columns cannot be d.",
      "Rows and columns can swap roles: two columns with d only in the same two rows remove d from those two rows.",
    ],
    spot: ["For each digit, list the rows (or columns) with exactly two places left for it.", "Two such rows with the same pair of columns form an X-Wing."],
    pitfalls: ["Eliminating in the wrong direction: when the base units are rows, eliminate along columns, and vice versa.", "The four corners do not need to be in four different boxes."],
  },
  skyscraper: {
    name: "Skyscraper",
    alias: "Skyscraper",
    summary: "Two parallel strong links share a base, so a cell that sees both tops cannot be d.",
    rule: "Two rows each with only 2 places for d, one end of each in the same column → remove d from cells that see both other ends.",
    idea: [
      "Picture two buildings side by side. In two rows (or two columns), digit d has exactly two places — each row is a strong link. One end of each (the \"bases\") lines up in the same column, while the other ends (the \"tops\") do not.",
      "The two bases share a column, so they cannot both be d; at least one base is not d, and then the top in its row must be d. So at least one of the two tops is d, and any cell that sees both tops loses d.",
      "A skyscraper is a skewed X-Wing: if the tops lined up as well, you would have an X-Wing.",
    ],
    spot: ["Find the rows (columns) with only two places for d, then pair up two rows that have one end in the same column."],
    pitfalls: ["Eliminating from cells that see the two bases instead of the two tops."],
  },
  "two-string-kite": {
    name: "2-String Kite",
    alias: "2-String Kite",
    summary: "A strong link in a row and one in a column, tied together in a box.",
    rule: "A row and a column each with only 2 places for d, one end of each in the same box → remove d from cells that see both other ends.",
    idea: [
      "In a row, d has only two places; in a column, d also has only two places. One end of the row and one end of the column sit in the same box (as two different cells). That is the knot of the kite.",
      "The two knot cells see each other, so they cannot both be d. Whichever of them is not d, the far end of its string is d. So at least one of the two free ends is d, and the cell where their row and column meet loses d.",
    ],
    spot: ["For each digit, find a row and a column with only two places, each having one end in the same box."],
    pitfalls: ["The two knot cells must be different cells."],
  },
  "xy-wing": {
    name: "XY-Wing",
    alias: "XY-Wing · Y-Wing",
    summary: "A pivot {x, y} sees two pincers {x, z} and {y, z}, so a cell that sees both pincers cannot be z.",
    rule: "Pivot {x, y}, pincers {x, z} and {y, z} → remove z from cells that see both pincers.",
    idea: [
      "It uses only bivalue cells. The pivot holds {x, y}; it sees one pincer {x, z} and another pincer {y, z}.",
      "If the pivot is x, the first pincer loses x and becomes z. If the pivot is y, the second pincer becomes z. There is no third option, so one pincer is certainly z. Any cell that sees both pincers cannot be z.",
      "It is the first three-step chain most players learn: assumption → consequence → consequence, packaged as a pattern you can spot at a glance.",
    ],
    spot: ["Mark the bivalue cells. Pick one as the pivot, then find two cells it sees that each share exactly one digit with it and share a third digit z with each other."],
    pitfalls: ["The pincers don't need to see each other, but both must see the pivot.", "Only z is eliminated, never x or y."],
  },
  "xyz-wing": {
    name: "XYZ-Wing",
    alias: "XYZ-Wing",
    summary: "Like an XY-Wing, but the pivot has three candidates {x, y, z}; z is removed only from cells that see all three cells.",
    rule: "Pivot {x, y, z}, pincers {x, z} and {y, z} → remove z from cells that see the pivot and both pincers.",
    idea: [
      "The pivot also holds z. If the pivot is x, the first pincer is z; if it is y, the second pincer is z; if it is z, the pivot itself is z. So z is in one of the three cells.",
      "An eliminated cell must see all three cells, so the elimination area is narrower than for an XY-Wing — usually a cell in the pivot's box and in the same row (column) as one pincer.",
    ],
    spot: ["Find a three-candidate cell, then two bivalue cells it sees that are subsets of it and share exactly the digit z."],
    pitfalls: ["Eliminating from a cell that sees only the two pincers is wrong: it must see the pivot too."],
  },
  "w-wing": {
    name: "W-Wing",
    alias: "W-Wing",
    summary: "Two far-apart cells with the same pair {x, y}, joined by a strong link on x, so a cell that sees both cannot be y.",
    rule: "Two {x, y} cells + a strong link on x joining them → remove y from cells that see both {x, y} cells.",
    idea: [
      "Two cells have the same two candidates {x, y} but do not see each other. If some unit has x in only two places L1 and L2, with L1 seeing the first cell and L2 seeing the second, you have a bridge.",
      "Suppose the first cell is not y → it is x → L1 is not x → L2 is x → the second cell is not x → the second cell is y. So at least one of the two cells is y.",
    ],
    spot: ["Find two identical bivalue cells far apart, then look for a strong link on one of their digits connecting them."],
    pitfalls: ["The bridge must be a strong link: a unit with exactly two places for x."],
  },
  swordfish: {
    name: "Swordfish",
    alias: "Swordfish · 3×3 fish",
    summary: "The X-Wing extended to three rows and three columns.",
    rule: "Three rows have d only within the same three columns → remove d from those columns in every other row.",
    idea: [
      "When three rows need three d's, and every place for d in those rows falls within three columns, each column gets exactly one d from those three rows. The other cells of the three columns have no room for d.",
      "Each row doesn't need all three places; 2 or 3 per row is fine, as long as together they use only three columns.",
      "Extending to four rows and four columns gives a Jellyfish, which is very rare. X-Wing, Swordfish and Jellyfish are together called fish patterns.",
    ],
    spot: ["List the rows with d in 2–3 places, and find three rows whose columns together number only three.", "If rows don't work, try columns."],
    pitfalls: ["A row with d in four places cannot take part.", "Eliminate only in the three cover columns, not in the three base rows."],
  },
  "simple-coloring": {
    name: "Simple Coloring",
    alias: "Simple Colors · Single's Chains",
    summary: "Join a digit's strong links into a chain and colour it in two alternating colours: exactly one colour is the answer.",
    rule: "A cell that sees both colours → remove d. Two cells of the same colour that see each other → that colour is false.",
    idea: [
      "Pick a digit d. Every unit with only two places for d gives a strong link: exactly one of the two cells is d. The links join up into chains.",
      "Colour along the chain alternately: blue, orange, blue, orange… Since each link has exactly one end that is d, either all blue cells are d or all orange cells are d.",
      "There are two rules. Trap: a cell outside the chain that sees both a blue and an orange cell sees a d whichever colour is true — eliminate. Wrap: two cells of the same colour that see each other mean that colour cannot be true — remove d from all cells of that colour, and every cell of the other colour is d.",
      "The Skyscraper and the 2-String Kite are really short colouring chains.",
    ],
    spot: ["Pick a digit with many strong links, and colour it with two pens right on the paper."],
    pitfalls: ["Join cells only with strong links. Joining two cells that merely see each other (a weak link) leads to wrong conclusions."],
  },
  "unique-rectangle": {
    name: "Unique Rectangle",
    alias: "Unique Rectangle Type 1",
    summary: "Avoid the pattern that would give a puzzle two solutions: the fourth corner cannot be left with only {x, y}.",
    rule: "3 corners of a rectangle (2 rows, 2 columns, 2 boxes) hold only {x, y} → remove x and y from the fourth corner.",
    idea: [
      "Take four cells at the corners of a rectangle spanning exactly two rows, two columns and two boxes. If all four held only {x, y}, you could swap x ↔ y in those cells and every row, column and box would still be valid — the puzzle would have two solutions. This is called a deadly pattern.",
      "A proper Sudoku always has exactly one solution. So if three corners are already down to {x, y}, the fourth must be some other digit: remove x and y from it.",
      "This technique relies on the puzzle having a unique solution. Use it only with puzzles from a trustworthy source.",
    ],
    spot: ["Find two cells with the same pair {x, y} in one row, in two different boxes; check whether the matching cells in another row close a rectangle."],
    pitfalls: [
      "The four cells must lie in exactly two boxes. Across four boxes, swapping breaks a box, so there is no deadly pattern.",
      "All four cells must be empty, not given digits.",
    ],
  },
  "bug-plus-one": {
    name: "BUG+1",
    alias: "Bivalue Universal Grave + 1",
    summary: "Every empty cell has two candidates except one with three: that cell takes the digit appearing three times in its units.",
    rule: "All cells have 2 candidates, one cell has 3 → it takes the digit that appears 3 times in its row, column and box.",
    idea: [
      "A BUG is a state where every empty cell has exactly two candidates and every digit appears exactly twice in each unit. Such a state never has exactly one solution.",
      "When the board is just one candidate away from a BUG — one cell with three, all others with two — the extra candidate must be that cell's answer, otherwise you fall into the BUG. The extra candidate is easy to find: it appears three times in the cell's row, column and box.",
    ],
    spot: ["It tends to appear at the end of hard puzzles, when the board is almost all bivalue cells.", "Count candidates in the row of the three-candidate cell: the digit that appears three times is the answer."],
    pitfalls: ["It applies only when exactly one cell has three candidates and every other empty cell has exactly two."],
  },
  "xy-chain": {
    name: "XY-Chain",
    alias: "XY-Chain",
    summary: "A chain of linked bivalue cells; if both ends contain z, a cell that sees both ends cannot be z.",
    rule: "A chain of bivalue cells whose two ends both contain z → remove z from cells that see both ends.",
    idea: [
      "Each bivalue cell is a switch: if it is not one digit, it is the other. Link cells that see each other and share a digit, and you get a chain that propagates.",
      "Suppose the first cell is not z → it is its other digit a → the next cell (holding a) is not a → it is its other digit b → … → the last cell is z. So if one end is not z, the other end is z: at least one end is z.",
      "An XY-Wing is an XY-Chain of three cells. Longer chains are stronger but harder to find; start from the bivalue cells that see the cell you want to eliminate from.",
    ],
    spot: ["Draw the bivalue cells on paper, and connect cells that see each other and share a digit.", "Choose z as the digit at both ends and walk from one end."],
    pitfalls: ["Each link must go the right way: the digit \"out\" of one cell must be the digit \"in\" to the next."],
  },
};
